/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComptesRouteImport } from './routes/comptes'
import { Route as DepensesRouteImport } from './routes/depenses'
import { Route as EnveloppesRouteImport } from './routes/enveloppes'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as RevenusRouteImport } from './routes/revenus'
import { Route as SouhaitsRouteImport } from './routes/souhaits'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComptesRoute = ComptesRouteImport.update({
  id: '/comptes',
  path: '/comptes',
  getParentRoute: () => rootRouteImport,
} as any)
const DepensesRoute = DepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => rootRouteImport,
} as any)
const EnveloppesRoute = EnveloppesRouteImport.update({
  id: '/enveloppes',
  path: '/enveloppes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenusRoute = RevenusRouteImport.update({
  id: '/revenus',
  path: '/revenus',
  getParentRoute: () => rootRouteImport,
} as any)
const SouhaitsRoute = SouhaitsRouteImport.update({
  id: '/souhaits',
  path: '/souhaits',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comptes': typeof ComptesRoute
  '/depenses': typeof DepensesRoute
  '/enveloppes': typeof EnveloppesRoute
  '/profil': typeof ProfilRoute
  '/revenus': typeof RevenusRoute
  '/souhaits': typeof SouhaitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comptes': typeof ComptesRoute
  '/depenses': typeof DepensesRoute
  '/enveloppes': typeof EnveloppesRoute
  '/profil': typeof ProfilRoute
  '/revenus': typeof RevenusRoute
  '/souhaits': typeof SouhaitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comptes': typeof ComptesRoute
  '/depenses': typeof DepensesRoute
  '/enveloppes': typeof EnveloppesRoute
  '/profil': typeof ProfilRoute
  '/revenus': typeof RevenusRoute
  '/souhaits': typeof SouhaitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comptes'
    | '/depenses'
    | '/enveloppes'
    | '/profil'
    | '/revenus'
    | '/souhaits'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comptes'
    | '/depenses'
    | '/enveloppes'
    | '/profil'
    | '/revenus'
    | '/souhaits'
  id:
    | '__root__'
    | '/'
    | '/comptes'
    | '/depenses'
    | '/enveloppes'
    | '/profil'
    | '/revenus'
    | '/souhaits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComptesRoute: typeof ComptesRoute
  DepensesRoute: typeof DepensesRoute
  EnveloppesRoute: typeof EnveloppesRoute
  ProfilRoute: typeof ProfilRoute
  RevenusRoute: typeof RevenusRoute
  SouhaitsRoute: typeof SouhaitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comptes': {
      id: '/comptes'
      path: '/comptes'
      fullPath: '/comptes'
      preLoaderRoute: typeof ComptesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depenses': {
      id: '/depenses'
      path: '/depenses'
      fullPath: '/depenses'
      preLoaderRoute: typeof DepensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enveloppes': {
      id: '/enveloppes'
      path: '/enveloppes'
      fullPath: '/enveloppes'
      preLoaderRoute: typeof EnveloppesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenus': {
      id: '/revenus'
      path: '/revenus'
      fullPath: '/revenus'
      preLoaderRoute: typeof RevenusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/souhaits': {
      id: '/souhaits'
      path: '/souhaits'
      fullPath: '/souhaits'
      preLoaderRoute: typeof SouhaitsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComptesRoute: ComptesRoute,
  DepensesRoute: DepensesRoute,
  EnveloppesRoute: EnveloppesRoute,
  ProfilRoute: ProfilRoute,
  RevenusRoute: RevenusRoute,
  SouhaitsRoute: SouhaitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
